### ISSUE TITLE
[CLOSED] IndexOutOfBoundsException -  78_caloriecount

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/evosuite-plus-plus#22]
<a href="https://github.com/lylytran"><img src="https://avatars0.githubusercontent.com/u/7779337?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lylytran](https://github.com/lylytran)**
_Friday Feb 01, 2019 at 07:44 GMT_
_Originally opened as https://github.com/llmhyy/evosuite_progress/issues/22_

----

Testcase:
#---------------------------------------------------------------------------
#Project=caloriecount  -  78_caloriecount
#---------------------------------------------------------------------------
com.lts.util.prop.PropertiesUtil#findRef(Ljava/util/Properties;)Lcom/lts/util/prop/PropertiesUtil$PropertyRef;

Log

ER] 15:41:29.002 [logback-2] ERROR MonotonicGA - Best fitness: 18.0, Coverage: 0.0
[MASTER] 15:41:29.112 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: org.dom4j.tree.ConcurrentReaderHashMap with seed 1549006882618. Configuration id : null
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_112]
	at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_112]
	at org.evosuite.coverage.fbranch.FBranchSuiteFitness.getFitness(FBranchSuiteFitness.java:100) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchSuiteFitness.getFitness(FBranchSuiteFitness.java:21) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.MonotonicGA.evolve(MonotonicGA.java:145) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.MonotonicGA.generateSolution(MonotonicGA.java:283) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.strategy.WholeTestSuiteStrategy.generateTests(WholeTestSuiteStrategy.java:117) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:659) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:241) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
* Computation finished
[MASTER] 15:41:29.224 [main] ERROR SearchStatistics - No obtained value for output variable: MutationScore
[MASTER] 15:41:31.235 [main] ERROR SearchStatistics - No obtained value for output variable: MutationScore
[MASTER] 15:41:32.240 [main] ERROR SearchStatistics - No obtained value for output variable: MutationScore
[MASTER] 15:41:33.245 [main] ERROR SearchStatistics - No obtained value for output variable: MutationScore
[MASTER] 15:41:34.248 [main] ERROR SearchStatistics - No obtained value for output variable: MutationScore

**Comment by llmhyy** [comment]
<a href="https://github.com/llmhyy"><img src="https://avatars1.githubusercontent.com/u/2909461?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [llmhyy](https://github.com/llmhyy)**
_Friday Feb 01, 2019 at 19:19 GMT_

----

It is not supposed to be. It means that the whole testsuite is empty. We need to reply that problem. In addition, does all the rest exception-methods have the same problem?
