### ISSUE TITLE
[CLOSED] NPE

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/evosuite-plus-plus#25]
<a href="https://github.com/lylytran"><img src="https://avatars0.githubusercontent.com/u/7779337?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lylytran](https://github.com/lylytran)**
_Saturday Feb 09, 2019 at 11:03 GMT_
_Originally opened as https://github.com/llmhyy/evosuite_progress/issues/25_

----

Hi Lin Yun,
I got this exception, note here, maybe you can check.
Thanks,
**Testcase:**

org.databene.jdbacl.model.DefaultDBColumn#getForeignKeyConstraint()Lorg/databene/jdbacl/model/DBForeignKeyConstraint;
org.databene.jdbacl.model.DefaultDBColumn#equals(Ljava/lang/Object;)Z

**Stacktrace:**

* Starting evolution
[Progress:>                             0%] [Cov:>                                  0%][MASTER] 18:52:11.144 [logback-1] WARN  MonotonicGA - monotonic ga
[MASTER] 18:52:12.559 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: org.databene.jdbacl.model.DefaultDBColumn with seed 1549709526404. Configuration id : null
java.lang.NullPointerException: null
	at org.evosuite.coverage.fbranch.FBranchTestFitness.findLastConstantInstructionInBlock(FBranchTestFitness.java:489) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchTestFitness.getReturnConstants(FBranchTestFitness.java:520) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchTestFitness.calculateReturnInsFitness(FBranchTestFitness.java:150) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchTestFitness.calculateInterproceduralFitness(FBranchTestFitness.java:136) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchTestFitness.getFitness(FBranchTestFitness.java:105) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchSuiteFitness.getTestFitness(FBranchSuiteFitness.java:402) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchSuiteFitness.getNewFitness(FBranchSuiteFitness.java:440) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchSuiteFitness.getFitness(FBranchSuiteFitness.java:568) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.coverage.fbranch.FBranchSuiteFitness.getFitness(FBranchSuiteFitness.java:32) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.GeneticAlgorithm.calculateFitnessAndSortPopulation(GeneticAlgorithm.java:599) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.MonotonicGA.initializePopulation(MonotonicGA.java:225) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.MonotonicGA.generateSolution(MonotonicGA.java:244) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.strategy.WholeTestSuiteStrategy.generateTests(WholeTestSuiteStrategy.java:117) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:659) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:241) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) ~[EvosuiteTest-1.0.6-SNAPSHOT.jar:1.0.6-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
* Computation finished
[MASTER] 18:52:12.669 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 18:52:12.774 [main] ERROR TestGeneration - failed to write statistics data
* EvoSuite 1.0.6-SNAPSHOT
* Going to generate test cases for class: org.databene.jdbacl.model.DefaultDBColumn
* Starting client
* Properties loaded from /Users/lylytran/Projects/Evosuite/experiments/SF100-testFilteredMethods/13_jdbacl/evosuite-files/evosuite.properties
* Connecting to master process on port 13936

**Comment by llmhyy** [comment]
<a href="https://github.com/llmhyy"><img src="https://avatars1.githubusercontent.com/u/2909461?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [llmhyy](https://github.com/llmhyy)**
_Saturday Feb 09, 2019 at 13:12 GMT_

----

fixed, thanks!
